name: Deploy to JFrog

on:
  push:
    branches:
      - main # Change this to your default branch

jobs:
  package_versioning:
    name: NPM Package Bump Up
    runs-on: ubuntu-latest
    timeout-minutes: 1

    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
     
      - name: Clean Package Name
        id: clean_package_name
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "Latest tag: $LATEST_TAG"
 
          CURRENT_VERSION="${LATEST_TAG//v/}"
          echo "Current version: $CURRENT_VERSION"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check Latest Version
        run: |
          echo $(git describe --tags --abbrev=0)

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Specify your Node.js version

      - name: Install dependencies
        run: npm install

      # - name: Configure NPM for JFrog
      #   run: |
      #     npm config set registry ${{ secrets.JFROG_REPO }}
      #     npm config set ${{ secrets.JFROG_URL }}:_authToken=${{ secrets.JFROG_API_KEY }}
      #     npm publish --access public # Adjust access level if necessary

      # - name: Publish to JFrog
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.JFROG_API_KEY }}
      #   run: |
      #     npm publish --access public # Adjust access level if necessary


# name: Print Latest Tag

# on:
#   push:
#     branches:
#       - main

# jobs:
#   print-latest-tag:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#         with:
#           fetch-depth: 0

#       - name: Print Latest Tag
#         run: |
#           git fetch --all --tags
#           echo "Latest tag: $(git describe --tags --abbrev=0)"
